// Author-hosted and publisher-authorized editions. See BOOK_SOURCES.md for provenance.
// PDF links point to the resource itself; the remote host controls inline reading or download.
export const books = [
  {
    id: 'dive-deep-learning',
    title: 'Dive into Deep Learning',
    authors: 'Aston Zhang, Zachary C. Lipton, Mu Li & Alexander J. Smola',
    category: 'deep-learning',
    level: 'Beginner',
    description: 'Build intuition and working models together. Follow executable examples from linear regression through attention, transformers, computer vision, and modern neural architectures.',
    format: 'PDF + notebooks',
    url: 'https://d2l.ai/d2l-en.pdf',
    sourceUrl: 'https://d2l.ai/',
    source: 'D2L authors',
    year: '2023',
    topics: ['PyTorch', 'Neural networks', 'Attention'],
    color: 'sage',
  },
  {
    id: 'understanding-deep-learning',
    title: 'Understanding Deep Learning',
    authors: 'Simon J. D. Prince',
    category: 'deep-learning',
    level: 'Intermediate',
    description: 'Explore neural networks through careful diagrams, experiments, and mathematics. Connect training fundamentals with transformers, diffusion, graph networks, and the questions behind generalization.',
    format: 'PDF + notebooks',
    url: 'https://github.com/udlbook/udlbook/releases/download/v5.0.3/UnderstandingDeepLearning_02_09_26_C.pdf',
    sourceUrl: 'https://udlbook.github.io/udlbook/',
    source: 'Author on GitHub',
    year: '2023',
    editionLabel: 'Author edition v5.0.3',
    accessNote: 'GitHub serves the PDF directly. Your browser may download it.',
    topics: ['Transformers', 'Diffusion', 'Optimization'],
    color: 'lavender',
  },
  {
    id: 'little-deep-learning',
    title: 'The Little Book of Deep Learning',
    authors: 'François Fleuret',
    category: 'deep-learning',
    level: 'Intermediate',
    description: 'A compact, phone-friendly tour for readers with a STEM background. Connect training, architectures, generative models, and efficient adaptation in a few focused sittings.',
    format: 'PDF',
    url: 'https://fleuret.org/public/lbdl.pdf',
    sourceUrl: 'https://fleuret.org/francois/lbdl.html',
    source: 'Author edition',
    year: '2026',
    editionLabel: 'Version 1.3',
    topics: ['Training', 'Generative models', 'Fine-tuning'],
    color: 'peach',
  },
  {
    id: 'neural-networks-deep-learning',
    title: 'Neural Networks and Deep Learning',
    authors: 'Michael Nielsen',
    category: 'deep-learning',
    level: 'Beginner',
    description: 'Start with handwritten digits and discover how a network learns. Interactive explanations make gradients, backpropagation, and the role of hidden layers feel tangible.',
    format: 'Online book',
    url: 'http://neuralnetworksanddeeplearning.com/',
    sourceUrl: 'http://neuralnetworksanddeeplearning.com/',
    source: 'Author website',
    year: '2015',
    topics: ['Backpropagation', 'Gradients', 'Neural networks'],
    color: 'blue',
  },
  {
    id: 'deep-learning',
    title: 'Deep Learning',
    authors: 'Ian Goodfellow, Yoshua Bengio & Aaron Courville',
    category: 'deep-learning',
    level: 'Advanced',
    description: 'A foundational reference connecting probability, optimization, representation learning, and deep generative models. Read the complete authorized web edition, with a chapter for every detour.',
    format: 'Online book',
    url: 'https://www.deeplearningbook.org/',
    sourceUrl: 'https://www.deeplearningbook.org/',
    source: 'Official MIT Press companion',
    year: '2016',
    topics: ['Representations', 'Probability', 'Generative models'],
    color: 'amber',
  },
  {
    id: 'deep-learning-foundations',
    title: 'Deep Learning: Foundations and Concepts',
    authors: 'Christopher M. Bishop & Hugh Bishop',
    category: 'deep-learning',
    level: 'Intermediate',
    description: 'Follow a visual, probability-based path from basic learning principles to modern deep architectures. The authors provide a free browser reader alongside the print edition.',
    format: 'Online book',
    url: 'https://www.bishopbook.com/',
    sourceUrl: 'https://www.bishopbook.com/',
    source: 'Official author reader',
    year: '2024',
    accessNote: 'Read free in the embedded browser reader on the author website.',
    topics: ['Probability', 'Architectures', 'Deep learning'],
    color: 'sage',
  },
  {
    id: 'fastai-book',
    title: 'Deep Learning for Coders',
    authors: 'Jeremy Howard & Sylvain Gugger',
    category: 'deep-learning',
    level: 'Beginner',
    description: 'Learn by building useful models first, then unpacking their internals. The authors share the book as readable, runnable notebooks covering vision, text, and tabular data.',
    format: 'Online book',
    url: 'https://github.com/fastai/fastbook',
    sourceUrl: 'https://github.com/fastai/fastbook',
    source: 'fast.ai on GitHub',
    year: '2020',
    editionLabel: 'Author notebook edition',
    topics: ['Practical projects', 'PyTorch', 'Computer vision'],
    color: 'peach',
  },
  {
    id: 'mathematics-ml',
    title: 'Mathematics for Machine Learning',
    authors: 'Marc Peter Deisenroth, A. Aldo Faisal & Cheng Soon Ong',
    category: 'foundations',
    level: 'Beginner',
    description: 'Grow the mathematical roots behind ML: vectors, calculus, probability, and optimization. Then see those ideas become regression, PCA, mixture models, and support vector machines.',
    format: 'PDF + notebooks',
    url: 'https://mml-book.github.io/book/mml-book.pdf',
    sourceUrl: 'https://mml-book.github.io/',
    source: 'Authors on GitHub',
    year: '2020',
    topics: ['Linear algebra', 'Probability', 'Calculus'],
    color: 'sage',
  },
  {
    id: 'isl-python',
    title: 'An Introduction to Statistical Learning with Python',
    authors: 'Gareth James, Daniela Witten, Trevor Hastie, Robert Tibshirani & Jonathan Taylor',
    category: 'machine-learning',
    level: 'Beginner',
    description: 'A welcoming route through regression, classification, resampling, trees, and deep learning. Python labs turn statistical ideas into experiments you can reproduce and extend.',
    format: 'PDF + notebooks',
    url: 'https://drive.google.com/uc?export=download&id=1ajFkHO6zjrdGNqhqW1jKBZdiNGh_8YQ1',
    sourceUrl: 'https://www.statlearning.com/',
    source: 'Official author download',
    year: '2023',
    editionLabel: 'Python edition',
    accessNote: 'The official author link opens a Google Drive PDF download. Your browser may save the file.',
    topics: ['Regression', 'Classification', 'Evaluation'],
    color: 'blue',
  },
  {
    id: 'elements-statistical-learning',
    title: 'The Elements of Statistical Learning',
    authors: 'Trevor Hastie, Robert Tibshirani & Jerome Friedman',
    category: 'machine-learning',
    level: 'Advanced',
    description: 'Go deeper into statistical prediction, regularization, kernels, ensembles, and unsupervised learning. This authorized second-edition PDF includes corrections from the twelfth printing.',
    format: 'PDF',
    url: 'https://drive.google.com/uc?export=download&id=1--Wo5Hcl2y_v3DL-tGgcJHRPdtjiVYjS',
    sourceUrl: 'https://hastie.su.domains/ElemStatLearn/main.html',
    source: 'Trevor Hastie, Stanford',
    year: '2009',
    editionLabel: 'Second edition, corrected twelfth printing',
    accessNote: 'The official author link opens a Google Drive PDF download. Your browser may save the file.',
    topics: ['Ensembles', 'Regularization', 'Statistical learning'],
    color: 'amber',
  },
  {
    id: 'probabilistic-ml-intro',
    title: 'Probabilistic Machine Learning: An Introduction',
    authors: 'Kevin P. Murphy',
    category: 'machine-learning',
    level: 'Intermediate',
    description: 'View prediction through uncertainty. This author-shared draft connects probability, decision theory, classical algorithms, and neural models, with notebooks that recreate many of its figures.',
    format: 'PDF + notebooks',
    url: 'https://github.com/probml/pml-book/releases/latest/download/book1.pdf',
    sourceUrl: 'https://probml.github.io/pml-book/book1.html',
    source: 'Author on GitHub',
    year: '2022',
    editionLabel: 'Freely shared author draft',
    accessNote: 'GitHub serves the PDF directly. Your browser may download it.',
    topics: ['Bayesian thinking', 'Decision theory', 'Neural networks'],
    color: 'lavender',
  },
  {
    id: 'probabilistic-ml-advanced',
    title: 'Probabilistic Machine Learning: Advanced Topics',
    authors: 'Kevin P. Murphy',
    category: 'machine-learning',
    level: 'Advanced',
    description: 'Explore inference, latent variables, generative modeling, and sequential decisions. The freely shared author draft links theory to practical notebook experiments and modern deep learning.',
    format: 'PDF + notebooks',
    url: 'https://github.com/probml/pml2-book/releases/latest/download/book2.pdf',
    sourceUrl: 'https://probml.github.io/pml-book/book2.html',
    source: 'Author on GitHub',
    year: '2023',
    editionLabel: 'Freely shared author draft',
    accessNote: 'GitHub serves the PDF directly. Your browser may download it.',
    topics: ['Inference', 'Generative models', 'Latent variables'],
    color: 'blue',
  },
  {
    id: 'speech-language-processing',
    title: 'Speech and Language Processing',
    authors: 'Dan Jurafsky & James H. Martin',
    category: 'llms',
    level: 'Intermediate',
    description: 'Trace language systems from tokens and embeddings to transformers, post-training, and retrieval. This evolving third-edition draft also covers speech and linguistic structure.',
    format: 'PDF',
    url: 'https://web.stanford.edu/~jurafsky/slp3/ed3book_aug26.pdf',
    sourceUrl: 'https://web.stanford.edu/~jurafsky/slp3/',
    source: 'Stanford author manuscript',
    year: '2026 draft',
    editionLabel: 'Third edition, August 19, 2026 draft',
    topics: ['LLMs', 'Transformers', 'RAG'],
    color: 'lavender',
  },
  {
    id: 'graph-representation-learning',
    title: 'Graph Representation Learning',
    authors: 'William L. Hamilton',
    category: 'deep-learning',
    level: 'Advanced',
    description: 'Learn to represent relationships, not just individual examples. This authorized author draft explores node embeddings, graph neural networks, knowledge graphs, and graph generation.',
    format: 'PDF',
    url: 'https://www.cs.mcgill.ca/~wlh/grl_book/files/GRL_Book.pdf',
    sourceUrl: 'https://www.cs.mcgill.ca/~wlh/grl_book/',
    source: 'Author at McGill',
    year: '2020',
    editionLabel: 'Authorized pre-publication draft',
    topics: ['Graph neural networks', 'Embeddings', 'Knowledge graphs'],
    color: 'sage',
  },
  {
    id: 'reinforcement-learning',
    title: 'Reinforcement Learning: An Introduction',
    authors: 'Richard S. Sutton & Andrew G. Barto',
    category: 'machine-learning',
    level: 'Intermediate',
    description: 'Follow an agent learning through rewards, exploration, and experience. The second edition develops bandits, value functions, temporal-difference learning, and policy gradients from first principles.',
    format: 'PDF',
    url: 'http://incompleteideas.net/book/RLbook2020.pdf',
    sourceUrl: 'http://incompleteideas.net/book/the-book-2nd.html',
    source: 'Richard Sutton, author',
    year: '2018',
    editionLabel: 'Second edition, corrected 2020 file',
    topics: ['Rewards', 'Q-learning', 'Policy gradients'],
    color: 'peach',
  },
  {
    id: 'ml-systems-foundations',
    title: 'Introduction to Machine Learning Systems',
    authors: 'Vijay Janapa Reddi & contributors',
    category: 'systems',
    level: 'Intermediate',
    description: 'Connect models to the machines that run them. Volume I covers data workflows, training, compression, acceleration, serving, and the trade-offs behind reliable ML systems.',
    format: 'PDF',
    url: 'https://mlsysbook.ai/vol1/assets/downloads/Machine-Learning-Systems-Vol1.pdf',
    sourceUrl: 'https://mlsysbook.ai/vol1/',
    source: 'Harvard ML Systems',
    year: '2026',
    topics: ['ML operations', 'Compression', 'Model serving'],
    color: 'blue',
  },
  {
    id: 'ml-systems-scale',
    title: 'Machine Learning Systems at Scale',
    authors: 'Vijay Janapa Reddi & contributors',
    category: 'systems',
    level: 'Advanced',
    description: 'Take ML beyond one machine. This open Volume II draft explores distributed training, communication, inference fleets, fault tolerance, and responsible operation at scale.',
    format: 'PDF',
    url: 'https://mlsysbook.ai/vol2/assets/downloads/Machine-Learning-Systems-Vol2.pdf',
    sourceUrl: 'https://mlsysbook.ai/vol2/',
    source: 'Harvard ML Systems',
    year: '2026 draft',
    editionLabel: 'Volume II, open draft',
    topics: ['Distributed training', 'Inference', 'Reliability'],
    color: 'amber',
  },
  {
    id: 'deep-learning-theory',
    title: 'The Principles of Deep Learning Theory',
    authors: 'Daniel A. Roberts, Sho Yaida & Boris Hanin',
    category: 'deep-learning',
    level: 'Advanced',
    description: 'An ambitious mathematical exploration of why deep networks behave as they do. The author preprint studies initialization, learning dynamics, representation, and finite-width effects.',
    format: 'PDF',
    url: 'https://arxiv.org/pdf/2106.10165',
    sourceUrl: 'https://arxiv.org/abs/2106.10165',
    source: 'Author preprint on arXiv',
    year: '2021 preprint',
    editionLabel: 'Author preprint v2',
    topics: ['Learning dynamics', 'Neural tangent kernels', 'Theory'],
    color: 'lavender',
  },
];

export const booksCheckedAt = '2026-10-09';
