// Original explanations. Reading links point to authors, course teams, or official docs.
const readings = {
  foundations: { title: 'Mathematics for Machine Learning', url: 'https://mml-book.github.io/' },
  ml: { title: 'Google Machine Learning Crash Course', url: 'https://developers.google.com/machine-learning/crash-course' },
  dl: { title: 'Dive into Deep Learning', url: 'https://d2l.ai/' },
  llm: { title: 'Hugging Face LLM Course', url: 'https://huggingface.co/learn/llm-course/chapter1/1' },
  systems: { title: 'Full Stack Deep Learning', url: 'https://fullstackdeeplearning.com/course/2022/' },
};

const topicReadings = {
  metrics: { title: 'Google: accuracy, recall, precision, and related metrics', url: 'https://developers.google.com/machine-learning/crash-course/classification/accuracy-precision-recall' },
  overfitting: { title: 'Google: overfitting and model complexity', url: 'https://developers.google.com/machine-learning/crash-course/overfitting/model-complexity' },
  attention: { title: 'Dive into Deep Learning: attention scoring functions', url: 'https://d2l.ai/chapter_attention-mechanisms-and-transformers/attention-scoring-functions.html' },
  tokenization: { title: 'Hugging Face: the tokenizers chapter', url: 'https://huggingface.co/learn/llm-course/chapter6/1' },
  lora: { title: 'Original paper: Low-Rank Adaptation of Large Language Models', url: 'https://arxiv.org/abs/2106.09685' },
  rag: { title: 'Original paper: Retrieval-Augmented Generation', url: 'https://arxiv.org/abs/2005.11401' },
  agents: { title: 'Anthropic: building effective agents', url: 'https://www.anthropic.com/engineering/building-effective-agents' },
  'ai-design-systems': { title: 'Google People + AI Guidebook', url: 'https://pair.withgoogle.com/guidebook/' },
};

export const concepts = [
  {
    id: 'vectors', title: 'Vectors & similarity', category: 'foundations', level: 'Beginner',
    summary: 'Turn objects into coordinates, then ask how close their directions are.',
    explanation: 'A vector is an ordered collection of numbers. In machine learning, those numbers can describe measurements, pixels, or a learned representation of meaning. Dot products combine corresponding coordinates. Cosine similarity divides that dot product by the vectors’ lengths, so it compares direction rather than size. Similarity is useful only when the representation and distance measure fit the task. Two vectors can be mathematically close without being equivalent for your application.',
    example: 'Represent a plant by height, leaf width, and water use. After appropriate scaling, nearby vectors can help identify plants with similar care needs.',
    takeaway: 'Coordinates need a meaningful representation. Distance alone does not create meaning.',
    formula: 'cosine(a, b) = (a · b) / (||a|| ||b||)', related: ['embeddings', 'pca', 'retrieval'], demo: 'embeddings',
    demoTitle: 'Rotate a vector', demoNote: 'A two-dimensional geometric example. Real learned embeddings usually have many more dimensions.',
  },
  {
    id: 'probability', title: 'Probability & uncertainty', category: 'foundations', level: 'Beginner',
    summary: 'Describe uncertainty with distributions instead of pretending every answer is certain.',
    explanation: 'A probability distribution assigns nonnegative probabilities to possible outcomes, with a total of one. Models often output scores that must be transformed or calibrated before they can be interpreted as probabilities. Conditional probability asks how expectations change when information is known. An accurate classifier is not automatically well calibrated: among cases assigned 80% confidence, approximately 80% should be correct if that confidence is well calibrated.',
    example: 'A weather model can assign 70% probability to rain. Across many comparable forecasts, calibration asks whether it rains about seven times in ten.',
    takeaway: 'Confidence is a claim about uncertainty. Check it against outcomes.',
    formula: 'P(A | B) = P(A and B) / P(B)', related: ['logistic-regression', 'decoding', 'evaluation'], demo: null,
    steps: ['Define the possible outcomes.', 'Assign probabilities that sum to one.', 'Compare predicted confidence with observed outcomes.'],
  },
  {
    id: 'loss-functions', title: 'Loss functions', category: 'foundations', level: 'Beginner',
    summary: 'Choose the signal that tells a model what getting better actually means.',
    explanation: 'A loss function turns a prediction and its target into a numerical penalty. Mean squared error makes large numerical mistakes especially costly. Cross-entropy scores the probability assigned to the correct class. Training minimizes an aggregate of these penalties, often with regularization. The chosen loss is a proxy for the real goal, so a lower training loss does not guarantee a more helpful product or better performance on unseen data.',
    example: 'For energy-demand prediction, squaring the error makes a large missed demand spike matter more than several small misses.',
    takeaway: 'A model optimizes the objective you give it, not the intention you leave unstated.',
    formula: 'MSE = mean((prediction − target)²)', related: ['linear-regression', 'gradient-descent', 'evaluation'], demo: 'regression',
    demoTitle: 'Make the residuals smaller', demoNote: 'Each vertical line is a residual. The readout calculates mean squared error for these fixed sample points.',
  },
  {
    id: 'gradient-descent', title: 'Gradient descent', category: 'foundations', level: 'Beginner',
    summary: 'Improve parameters by taking steps against the local slope of the loss.',
    explanation: 'A gradient describes how a function changes with respect to each parameter. Gradient descent subtracts a scaled gradient from the current parameters. The learning rate controls the step size: a tiny value moves slowly, while an overly large value can oscillate or diverge. Neural networks usually estimate gradients from minibatches. Their loss landscapes are far more complex than this bowl-shaped example, but the local update rule is the same.',
    example: 'A model that overpredicts electricity use adjusts its weights in the direction that reduces the average prediction penalty.',
    takeaway: 'A steeper slope is useful information, not permission to take an arbitrarily large step.',
    formula: 'w_next = w − learning_rate × gradient(loss)', related: ['loss-functions', 'backpropagation', 'normalization'], demo: 'gradient',
    demoTitle: 'Walk down a loss bowl', demoNote: 'The toy objective is L(w) = (w − 3)². Try a learning rate above one to see instability.',
  },
  {
    id: 'data-splits', title: 'Train, validation & test', category: 'foundations', level: 'Beginner',
    summary: 'Keep a fair final exam separate from both learning and model selection.',
    explanation: 'The training set fits parameters. A validation set helps choose models and hyperparameters. A test set estimates performance after those choices are complete. Splitting must match the real deployment scenario: future forecasting needs time-aware splits, while multiple records from one person may need to stay together. Fit preprocessing on the training set only. Repeatedly selecting changes based on test results gradually turns the test set into another validation set.',
    example: 'For a demand forecast, train on earlier months and test on later months instead of randomly mixing tomorrow’s data into the past.',
    takeaway: 'Data leakage can make an impressive evaluation meaningless.', related: ['overfitting', 'evaluation', 'mlops'], demo: null,
    steps: ['Train: learn parameters using past examples.', 'Validate: compare choices without fitting to these labels.', 'Test: measure the selected approach on untouched data.'],
  },
  {
    id: 'overfitting', title: 'Overfitting & generalization', category: 'foundations', level: 'Beginner',
    summary: 'Learn a useful pattern without memorizing every wobble in the examples.',
    explanation: 'Overfitting happens when a model captures quirks of the training sample that do not transfer to new data. Underfitting happens when the model cannot represent enough of the useful pattern. Model complexity, dataset size, noise, optimization, and regularization all affect generalization. Training and validation curves provide evidence, but the familiar U-shaped test-error curve is a teaching pattern rather than a universal law. Evaluate on data that resembles the setting you care about.',
    example: 'A high-degree curve can pass through noisy plant-growth measurements while making implausible predictions between them.',
    takeaway: 'The best fit to yesterday’s observations is not always the best prediction for tomorrow.', related: ['data-splits', 'dropout', 'ensembles'], demo: 'overfit',
    demoTitle: 'Change the curve’s complexity', demoNote: 'A polynomial is fitted to fixed noisy training data. The holdout error uses separate fixed points.',
  },
  {
    id: 'linear-regression', title: 'Linear regression', category: 'machine-learning', level: 'Beginner',
    summary: 'Predict a continuous quantity using a weighted combination of features.',
    explanation: 'Linear regression predicts a numerical target from an intercept plus weighted input features. A common fitting method minimizes squared residuals, which are the differences between observed and predicted values. Linear refers to the parameters: transformed features can still represent curved relationships. Inspect residuals and held-out error to understand what the model misses. A fitted coefficient describes an association under the model’s assumptions; it does not by itself establish a causal effect.',
    example: 'Estimate a home’s energy consumption using floor area, outside temperature, and occupancy.',
    takeaway: 'A simple baseline is valuable because its mistakes are easier to inspect.', formula: 'prediction = slope × x + intercept', related: ['loss-functions', 'gradient-descent', 'overfitting'], demo: 'regression',
    demoTitle: 'Fit a line by hand', demoNote: 'Adjust slope and intercept. Watch the predictions, residuals, and squared error respond together.',
  },
  {
    id: 'logistic-regression', title: 'Logistic regression', category: 'machine-learning', level: 'Beginner',
    summary: 'Map a linear score to a probability for a binary outcome.',
    explanation: 'Despite its name, logistic regression is commonly used for classification. It maps a weighted sum of features through the sigmoid function to produce a value between zero and one. Training typically minimizes binary cross-entropy. A decision threshold converts the score into a class label, and changing that threshold changes the tradeoff between missed positives and false alarms. The predicted values still need calibration checks if they will be used as probabilities.',
    example: 'Estimate whether an incoming support ticket is urgent, then choose a threshold that reflects the cost of overlooking an urgent request.',
    takeaway: 'Learning a score and choosing an action threshold are different decisions.', formula: 'sigmoid(z) = 1 / (1 + exp(−z))', related: ['probability', 'classification', 'metrics'], demo: 'classification',
    demoTitle: 'Choose a decision threshold', demoNote: 'These are fixed illustrative model scores. The demo evaluates the threshold; it does not fit logistic-regression weights.',
  },
  {
    id: 'classification', title: 'Decision boundaries', category: 'machine-learning', level: 'Beginner',
    summary: 'See where a model changes its answer from one class to another.',
    explanation: 'A classifier divides its input space into regions associated with different labels. The boundary can be a straight line, many axis-aligned rules, or a complex nonlinear surface. For a scored binary classifier, a threshold determines when the prediction becomes positive. That threshold should reflect error costs and the operating environment. A boundary learned from one population can perform poorly if the data distribution or class prevalence changes.',
    example: 'A quality-control system can prioritize catching defective components, accepting extra manual checks as the cost of a lower threshold.',
    takeaway: 'The right boundary depends on the cost of each kind of mistake.', related: ['logistic-regression', 'metrics', 'decision-trees'], demo: 'classification',
    demoTitle: 'Move the action boundary', demoNote: 'Gold and green points show true labels. Their position is a fixed predicted score, and the line is the decision threshold.',
  },
  {
    id: 'metrics', title: 'Precision, recall & F1', category: 'machine-learning', level: 'Beginner',
    summary: 'Ask which mistakes a single accuracy score might be hiding.',
    explanation: 'Precision measures how many predicted positives are truly positive. Recall measures how many actual positives were found. F1 is their harmonic mean, with equal emphasis on both. Accuracy can look excellent when one class dominates, even if the minority class is mostly missed. Metrics need a defined positive class, decision threshold, and evaluation population. Report the confusion matrix and choose measures that reflect the real consequences of errors.',
    example: 'For a document search, precision asks how many returned documents are useful; recall asks how many useful documents were found.',
    takeaway: 'Choose the metric after understanding the decision and its costs.', formula: 'precision = TP / (TP + FP) · recall = TP / (TP + FN)', related: ['classification', 'evaluation', 'retrieval'], demo: 'classification',
    demoTitle: 'Watch the confusion matrix change', demoNote: 'The four counts and derived metrics are recalculated for every threshold. Undefined ratios are shown as n/a.',
  },
  {
    id: 'decision-trees', title: 'Decision trees', category: 'machine-learning', level: 'Beginner',
    summary: 'Make predictions through a sequence of questions about the features.',
    explanation: 'A decision tree repeatedly partitions examples using feature-based rules. Training selects splits that improve an objective, such as reducing class impurity or squared error. Leaves produce class probabilities or numerical predictions. Small trees can be understandable, but deeper trees can memorize data and become sensitive to small changes in the training sample. Depth limits, minimum leaf sizes, and pruning are ways to control that complexity.',
    example: 'A plant-care model first checks soil moisture, then light exposure, and ends with a watering recommendation learned from labeled examples.',
    takeaway: 'A readable sequence of rules is still a learned model that needs validation.', related: ['ensembles', 'overfitting', 'classification'], demo: null,
    steps: ['Ask a feature question: is moisture below 30%?', 'Follow the corresponding branch to another question.', 'At the leaf, aggregate training examples into a prediction.'],
  },
  {
    id: 'ensembles', title: 'Forests & boosting', category: 'machine-learning', level: 'Intermediate',
    summary: 'Combine multiple models so their strengths complement one another.',
    explanation: 'Ensembles combine predictions from several models. Random forests train diverse trees with resampled data and feature randomness, then aggregate their outputs. Gradient boosting builds models sequentially to reduce the current ensemble’s loss. These approaches work differently, and neither guarantees improvement for every dataset. Diversity matters: averaging many models that make the same mistakes adds little. Use held-out evaluation and account for inference cost as well as predictive performance.',
    example: 'For tabular demand forecasting, compare a single tree with a forest and a boosted ensemble using the same time-based validation split.',
    takeaway: 'Several models help when their errors and strengths differ in useful ways.', related: ['decision-trees', 'overfitting', 'evaluation'], demo: null,
    steps: ['Forest: train varied trees independently.', 'Boosting: add models that improve the existing ensemble.', 'Combine outputs and check performance on unseen examples.'],
  },
  {
    id: 'clustering', title: 'K-means clustering', category: 'machine-learning', level: 'Beginner',
    summary: 'Discover groups by alternating between assignments and moving centers.',
    explanation: 'K-means starts with a chosen number of centers. Each example is assigned to its nearest center, then each center moves to the mean of its assigned examples. Repeating these steps reduces the within-cluster sum of squared distances until the assignments stabilize. Initialization and feature scaling matter. The method favors compact clusters in Euclidean space and does not automatically discover the correct number of groups or meaningful human categories.',
    example: 'Group environmental sensor readings with similar temperature and humidity patterns, then inspect whether the groups are useful.',
    takeaway: 'Clusters are patterns produced by a distance rule, not automatically ground truth.', formula: 'center_k = mean(points assigned to cluster k)', related: ['vectors', 'pca', 'embeddings'], demo: 'clustering',
    demoTitle: 'Grow three clusters', demoNote: 'Each click performs one assignment-and-update cycle on a fixed two-dimensional dataset.',
  },
  {
    id: 'pca', title: 'Principal component analysis', category: 'machine-learning', level: 'Intermediate',
    summary: 'Find directions that preserve as much variation as possible in fewer dimensions.',
    explanation: 'Principal component analysis finds orthogonal directions of maximum variance in centered data. Projecting onto the first few components gives a lower-dimensional linear representation. Scaling changes which features dominate, so choose it deliberately. PCA can help with compression, visualization, and noise reduction, but high variance is not the same as predictive usefulness. A two-dimensional plot can hide important structure from the original space.',
    example: 'Compress correlated measurements of leaf length, width, area, and perimeter into a smaller set of combined shape features.',
    takeaway: 'The directions with the most variation are not necessarily the most relevant to your labels.', related: ['vectors', 'clustering', 'embeddings'], demo: null,
    steps: ['Center the feature columns and choose whether to scale.', 'Find orthogonal directions with the largest variance.', 'Project onto a smaller number of those directions.'],
  },
  {
    id: 'neurons', title: 'Neural networks', category: 'deep-learning', level: 'Beginner',
    summary: 'Build flexible functions by composing weighted sums and nonlinear activations.',
    explanation: 'A basic neural unit combines inputs using learned weights and a bias, then applies an activation function. Layers compose many such operations so the network can represent complex relationships. The architecture determines how information flows, while training adjusts parameters to reduce a loss. A network’s units should not be treated as literal biological neurons. Their value comes from learning useful numerical representations from data.',
    example: 'A network can combine color and texture measurements into features that help classify a leaf image.',
    takeaway: 'Without nonlinear operations, a stack of dense linear layers is still a linear transformation.', formula: 'activation = f(w₁x₁ + w₂x₂ + bias)', related: ['activations', 'backpropagation', 'normalization'], demo: 'network',
    demoTitle: 'Send a signal through a tiny network', demoNote: 'This fixed 2 → 3 → 1 network computes a real forward pass. It does not train or recognize objects.',
  },
  {
    id: 'backpropagation', title: 'Backpropagation', category: 'deep-learning', level: 'Intermediate',
    summary: 'Use the chain rule to find how each parameter contributes to the loss.',
    explanation: 'Backpropagation efficiently computes gradients through a composition of differentiable operations. A forward pass calculates predictions and loss. A backward pass works through the computation graph, reusing intermediate derivatives to obtain gradients for the parameters. An optimizer then updates the parameters; backpropagation itself is not that update rule. Modern automatic differentiation systems handle the bookkeeping, but understanding the graph helps diagnose missing gradients and unstable training.',
    example: 'If a leaf classifier is confidently wrong, the loss gradient propagates through the output and earlier layers before the optimizer changes their weights.',
    takeaway: 'Backpropagation computes the directions. The optimizer chooses how to move.', related: ['gradient-descent', 'neurons', 'activations'], demo: null,
    steps: ['Forward: compose operations to compute a loss.', 'Backward: apply the chain rule through the graph.', 'Update: let the optimizer use the calculated gradients.'],
  },
  {
    id: 'activations', title: 'Activation functions', category: 'deep-learning', level: 'Beginner',
    summary: 'Introduce the nonlinear behavior that lets networks learn richer patterns.',
    explanation: 'Activation functions transform the weighted input of a unit. ReLU returns zero for negative inputs and passes positive inputs through. Sigmoid compresses values into the interval from zero to one, while tanh ranges from minus one to one. Their gradients behave differently, which affects optimization. An activation choice depends on the architecture and the role of the layer; output activations also depend on the prediction task.',
    example: 'A hidden unit can stay inactive until a combination of input measurements crosses its learned threshold.',
    takeaway: 'Activations shape both the forward signal and the gradients used to learn.', formula: 'ReLU(z) = max(0, z)', related: ['neurons', 'backpropagation', 'logistic-regression'], demo: 'network',
    demoTitle: 'Switch the hidden activation', demoNote: 'Keep weights fixed and compare ReLU with tanh. Only the hidden activation changes.',
  },
  {
    id: 'convolutions', title: 'Convolutions', category: 'deep-learning', level: 'Intermediate',
    summary: 'Slide a shared local filter across an input to detect spatial patterns.',
    explanation: 'A convolutional layer applies learned filters to local neighborhoods, reusing the same weights across locations. This parameter sharing helps detect patterns such as edges wherever they occur. In most deep-learning libraries, the operation called convolution is technically cross-correlation because the kernel is not flipped. Channels, padding, stride, and dilation determine how the operation behaves. Deeper layers can combine simple local features into more complex representations.',
    example: 'An edge filter responds where image brightness changes sharply, giving later layers information about shape boundaries.',
    takeaway: 'A filter is a local pattern detector whose weights are shared across the image.', formula: 'output[row, col] = sum(patch × kernel)', related: ['pooling', 'neurons', 'transfer-learning'], demo: 'convolution',
    demoTitle: 'Slide an edge detector', demoNote: 'A 3 × 3 kernel scans a fixed 6 × 6 image with stride one and no padding. The multiply-and-sum result is exact.',
  },
  {
    id: 'pooling', title: 'Pooling & receptive fields', category: 'deep-learning', level: 'Intermediate',
    summary: 'Summarize local regions and understand how much input a feature can see.',
    explanation: 'Pooling aggregates neighboring features, often by taking a maximum or average. It can reduce spatial resolution and computation, while discarding some location detail. A receptive field is the portion of the original input that can influence a particular unit. Stacking layers, changing stride, or using dilation can enlarge that field. Downsampling is useful in many architectures, but dense prediction tasks may need to recover or preserve fine spatial information.',
    example: 'A classifier may only need to know that a leaf vein exists in a region, while a segmentation model needs its precise position.',
    takeaway: 'Reducing resolution is a tradeoff between efficiency and spatial detail.', related: ['convolutions', 'neurons', 'transfer-learning'], demo: null,
    steps: ['Group a feature map into local windows.', 'Summarize each window using a maximum or average.', 'Track which original pixels can influence later features.'],
  },
  {
    id: 'dropout', title: 'Regularization & dropout', category: 'deep-learning', level: 'Intermediate',
    summary: 'Constrain learning so a model depends less on accidental training patterns.',
    explanation: 'Regularization changes training to encourage solutions that generalize. Weight penalties discourage certain parameter configurations. Dropout randomly suppresses selected activations during training, reducing reliance on particular co-adapted units. Early stopping uses validation behavior to decide when to stop fitting. These methods address different issues and require tuning. Standard dropout is disabled or handled with the appropriate scaling at ordinary inference time, depending on the implementation.',
    example: 'A small image classifier can use augmentation and dropout to reduce memorization when labeled photos are limited.',
    takeaway: 'Regularization should improve validation behavior, not merely make training harder.', related: ['overfitting', 'data-splits', 'neurons'], demo: null,
    steps: ['Observe training and validation performance.', 'Introduce a constraint, noise source, or stopping rule.', 'Tune its strength using validation data.'],
  },
  {
    id: 'normalization', title: 'Normalization', category: 'deep-learning', level: 'Intermediate',
    summary: 'Manage the scale of inputs and internal signals to make optimization easier.',
    explanation: 'Feature standardization uses training-set statistics to bring input measurements onto comparable scales. Internal normalization layers work differently. Batch normalization uses batch-related statistics during training and commonly running estimates at inference. Layer normalization normalizes across a feature dimension for each example and is common in transformer architectures. Details depend on the layer configuration. Neither operation removes the need to inspect data quality or prevent leakage from validation and test sets.',
    example: 'Without scaling, a distance-based model may treat a temperature measured in tiny units as much more important than humidity.',
    takeaway: 'Always ask which dimensions are normalized and which data supplied the statistics.', related: ['vectors', 'gradient-descent', 'transformers'], demo: null,
    steps: ['Identify which axes or features need normalization.', 'Compute the appropriate mean and variance.', 'Normalize, then apply learned scale and shift where the layer uses them.'],
  },
  {
    id: 'transfer-learning', title: 'Transfer learning', category: 'deep-learning', level: 'Intermediate',
    summary: 'Adapt useful representations learned on one task to another task.',
    explanation: 'Transfer learning starts from a model trained on another dataset or objective. You can freeze its representations and train a small task-specific head, or fine-tune some or all of the model. This can reduce the amount of labeled data and compute required, but the benefit depends on how well the learned features match the new domain. Evaluate carefully when inputs differ substantially from the pretraining distribution.',
    example: 'Start a flower classifier with an image encoder that already recognizes common visual patterns, then learn the flower categories.',
    takeaway: 'Reuse is a starting advantage, not a guarantee of domain expertise.', related: ['fine-tuning', 'convolutions', 'evaluation'], demo: null,
    steps: ['Choose a pretrained representation suited to the inputs.', 'Freeze it or fine-tune selected parameters.', 'Measure performance on the target domain.'],
  },
  {
    id: 'tokenization', title: 'Tokenization', category: 'llms', level: 'Beginner',
    summary: 'Translate text into the discrete pieces a language model can process.',
    explanation: 'A tokenizer converts text into token identifiers. Tokens may represent whole words, word fragments, punctuation, bytes, or other units, depending on the tokenizer. The model looks up numerical embeddings for these identifiers. Token boundaries and counts vary between models and languages, so a token is not a universal unit of meaning. Special tokens can mark roles or boundaries. Use the actual model’s tokenizer when measuring input length.',
    example: 'A rare technical word may be split into several pieces, while a frequent word may use a single token.',
    takeaway: 'Text length in characters or words does not reliably predict its token count.', related: ['embeddings', 'transformers', 'decoding'], demo: null,
    steps: ['Apply the tokenizer’s text-processing rules.', 'Split using its learned vocabulary and algorithm.', 'Map pieces to IDs, then look up their embeddings.'],
  },
  {
    id: 'embeddings', title: 'Embeddings', category: 'llms', level: 'Beginner',
    summary: 'Represent items as learned vectors that make useful relationships measurable.',
    explanation: 'Embeddings map discrete or structured items into numerical vectors. A model’s objective shapes which relationships those vectors preserve. A token embedding, a contextual token representation, and a sentence embedding are related ideas but not interchangeable outputs. Similarity search commonly compares normalized vectors using cosine similarity or dot products. The resulting score is a geometric measure, not automatically a probability that two statements mean the same thing.',
    example: 'A retrieval encoder can place a question about watering orchids near a care guide even when the wording differs.',
    takeaway: 'Choose an embedding model and similarity measure for the task, then test relevance.', related: ['vectors', 'retrieval', 'rag'], demo: 'embeddings',
    demoTitle: 'Explore cosine similarity', demoNote: 'These are hand-built two-dimensional vectors, not actual text embeddings. They expose the geometry used in many similarity systems.',
  },
  {
    id: 'attention', title: 'Attention', category: 'llms', level: 'Intermediate',
    summary: 'Let each position combine information from other positions using learned relevance scores.',
    explanation: 'Attention compares a query with keys to produce scores, normalizes those scores into weights, and takes a weighted combination of values. Scaled dot-product attention divides query-key dot products by the square root of the key dimension before softmax. Masks can restrict which positions are visible. Attention weights reveal part of a computation, but should not automatically be interpreted as a faithful explanation of the model’s overall reasoning.',
    example: 'In a sentence, a pronoun’s representation can incorporate information from earlier words through attention.',
    takeaway: 'Attention is a learned information-mixing operation, not a proof of understanding.', formula: 'attention(Q, K, V) = softmax(QKᵀ / √d) V', related: ['transformers', 'embeddings', 'decoding'], demo: 'attention',
    demoTitle: 'Mix values with attention weights', demoNote: 'A single toy query attends to four fixed keys. Temperature is an exploratory control over score sharpness, not an extra required transformer component.',
  },
  {
    id: 'transformers', title: 'Transformer blocks', category: 'llms', level: 'Intermediate',
    summary: 'Combine attention, feed-forward layers, and residual paths into reusable building blocks.',
    explanation: 'A transformer block combines attention with position-wise feed-forward computation, residual connections, and normalization. Positional information lets it distinguish order. Encoder, decoder, and encoder-decoder variants have different visibility rules and use cases. Decoder-only language models typically use causal masking so a position cannot attend to future tokens during next-token training. Many modern architectures modify the original design, so the exact normalization placement, activations, and attention variants differ.',
    example: 'A decoder processes the current text context and produces scores for the next token, then repeats after a token is selected.',
    takeaway: 'A transformer is an architecture. Its capabilities also depend on data, objectives, and training.', related: ['attention', 'normalization', 'decoding'], demo: null,
    steps: ['Embed tokens and incorporate position information.', 'Mix context through masked or unmasked attention.', 'Transform features and preserve residual paths across stacked blocks.'],
  },
  {
    id: 'decoding', title: 'Sampling & temperature', category: 'llms', level: 'Intermediate',
    summary: 'Turn next-token scores into a generation decision.',
    explanation: 'A language model outputs logits for candidate next tokens. Softmax converts scaled logits into a probability distribution. Lower temperature concentrates probability on higher-scoring candidates; higher temperature spreads it more broadly. Greedy decoding selects the highest-scoring token, while sampling draws from a distribution, sometimes restricted by top-k or top-p rules. Temperature changes diversity and predictability, but it is not a reliable control for truthfulness or factual accuracy.',
    example: 'For a creative writing exercise, broader sampling can produce more varied continuations from the same opening sentence.',
    takeaway: 'A fluent or confident continuation can still be wrong at any temperature.', formula: 'P(token_i) = exp(logit_i / T) / sum(exp(logit_j / T))', related: ['probability', 'attention', 'evaluation'], demo: 'attention',
    demoTitle: 'Change a softmax distribution', demoNote: 'Attention and token sampling both use softmax. Here, view the four scores as candidate logits; the weighted-value readout belongs to the attention illustration, not text generation.',
  },
  {
    id: 'fine-tuning', title: 'Fine-tuning', category: 'llms', level: 'Intermediate',
    summary: 'Update model parameters to adapt behavior to a task or domain.',
    explanation: 'Fine-tuning continues training a pretrained model on selected examples or objectives. It can improve formatting, task behavior, or domain performance when the data and evaluation are well designed. Full fine-tuning changes many parameters; parameter-efficient methods change a smaller subset or add compact trainable components. It is different from placing documents in a prompt. Fine-tuning is not a dependable substitute for a searchable source of frequently changing facts.',
    example: 'Train on reviewed examples so a model consistently extracts the same structured fields from maintenance reports.',
    takeaway: 'High-quality examples and a held-out evaluation matter more than simply running more updates.', related: ['lora', 'transfer-learning', 'rag'], demo: null,
    steps: ['Define a measurable target behavior.', 'Create and split representative training examples.', 'Update parameters and compare against the original model.'],
  },
  {
    id: 'lora', title: 'LoRA & efficient adaptation', category: 'llms', level: 'Advanced',
    summary: 'Learn a compact low-rank update while keeping the original weights fixed.',
    explanation: 'Low-Rank Adaptation represents an update to a weight matrix as the product of two smaller trainable matrices. The original matrix remains frozen. If the chosen rank is small, this greatly reduces the number of trainable parameters and optimizer states. It does not remove the cost of running the base model. Which layers receive adapters, the rank, and the training data all affect results. Some deployments merge the update into the base weights.',
    example: 'Adapt a language model to a specialized output format while storing a small adapter for each task.',
    takeaway: 'Parameter-efficient training still needs compute, suitable data, and careful evaluation.', formula: 'adapted weight = frozen weight + B × A', related: ['fine-tuning', 'vectors', 'evaluation'], demo: null,
    steps: ['Freeze the pretrained weight matrix.', 'Train two smaller matrices whose product forms an update.', 'Apply or merge that update during inference.'],
  },
  {
    id: 'rag', title: 'Retrieval-augmented generation', category: 'llms', level: 'Intermediate',
    summary: 'Retrieve relevant evidence before asking a model to compose an answer.',
    explanation: 'A RAG system combines retrieval with generation. Documents are prepared and indexed, a question retrieves candidate passages, and selected evidence is placed in the model’s context. The model then produces an answer, ideally with citations that can be checked. Retrieval can provide fresh or private information without updating model weights. It does not guarantee correctness: missing evidence, misleading passages, and unsupported synthesis can all produce failures.',
    example: 'A garden assistant retrieves current nursery care notes before answering a question about a particular orchid variety.',
    takeaway: 'Evaluate retrieval quality and answer faithfulness separately.', related: ['retrieval', 'reranking', 'evaluation'], demo: 'retrieval',
    demoTitle: 'Retrieve before composing', demoNote: 'This local miniature uses transparent token-overlap ranking. It shows retrieval only; no language model generates an answer.',
  },
  {
    id: 'retrieval', title: 'Search & retrieval', category: 'systems', level: 'Intermediate',
    summary: 'Find useful evidence in a collection before reasoning over it.',
    explanation: 'Retrieval selects candidate items from a corpus for a query. Lexical methods use word-level matches, while dense retrieval compares learned representations. Hybrid search combines signals from both. Chunk boundaries, metadata filters, access controls, and query wording all affect which evidence reaches later stages. A similarity score is specific to the method and should not be treated as universal confidence. Evaluate with realistic queries and known relevant evidence.',
    example: 'A query about shade-loving plants can combine exact species-name matches with semantic matches about low-light conditions.',
    takeaway: 'If the right evidence is missing from the candidates, generation cannot reliably recover it.', related: ['embeddings', 'rag', 'reranking'], demo: 'retrieval',
    demoTitle: 'Search a tiny garden library', demoNote: 'The visible ranking uses the Jaccard overlap of lowercase word sets, a simple lexical baseline rather than vector search.',
  },
  {
    id: 'reranking', title: 'Reranking', category: 'systems', level: 'Intermediate',
    summary: 'Spend extra attention on a shortlist to improve the order of retrieved evidence.',
    explanation: 'A first-stage retriever quickly collects candidates. A reranker then applies a more expensive scoring method to each query-candidate pair. A cross-encoder, for example, can read the query and passage together rather than comparing separately computed vectors. Reranking can improve precision near the top of the results, but it adds latency and cannot recover documents excluded by the initial retrieval stage. The final context also needs deduplication and sensible ordering.',
    example: 'After retrieving thirty care-guide passages, a reranker promotes the ones that directly answer a watering question.',
    takeaway: 'Candidate recall sets a ceiling on what a reranker can rescue.', related: ['retrieval', 'rag', 'evaluation'], demo: null,
    steps: ['Retrieve a broad, inexpensive candidate set.', 'Score each query and passage together with a stronger model.', 'Select useful, diverse evidence within the context budget.'],
  },
  {
    id: 'evaluation', title: 'Evaluation & failure analysis', category: 'systems', level: 'Intermediate',
    summary: 'Turn vague impressions of quality into repeatable evidence.',
    explanation: 'Evaluation begins with a clear task and representative cases. Measure the properties that matter, such as correctness, relevance, citation support, latency, cost, and behavior when information is missing. Slice results by scenario so a strong average cannot hide a weak subgroup. Automated checks can be combined with human review. Model-based judges can help at scale, but they have biases and need validation against reliable judgments.',
    example: 'An answer assistant is tested separately on answerable questions, ambiguous requests, outdated documents, and cases with no supporting evidence.',
    takeaway: 'A useful evaluation includes the situations where the system should ask, abstain, or fail gracefully.', related: ['metrics', 'data-splits', 'ai-design-systems'], demo: 'classification',
    demoTitle: 'Inspect errors before choosing a score', demoNote: 'This binary toy task illustrates metric tradeoffs. Evaluating an LLM system also requires task-specific checks and reviewed examples.',
  },
  {
    id: 'agents', title: 'Agents & tool use', category: 'systems', level: 'Intermediate',
    summary: 'Let a model choose actions within a controlled loop of tools and observations.',
    explanation: 'An agentic system uses a model to choose actions, call tools, observe results, and decide what to do next. A fixed workflow follows predefined control flow; an agent delegates more of that choice to the model. Tool schemas, permission boundaries, budgets, timeouts, and stopping conditions are part of the design. More autonomy is not automatically better. Reliable systems verify important tool outputs and keep consequential actions reviewable.',
    example: 'A research assistant can search a document collection, inspect selected passages, and draft a cited summary within a bounded number of steps.',
    takeaway: 'Give the system the minimum authority and autonomy required to complete the task.', related: ['rag', 'evaluation', 'ai-design-systems'], demo: null,
    steps: ['Observe the request and current state.', 'Choose an allowed tool and validate its arguments.', 'Inspect the result, then continue, ask, or finish within a budget.'],
  },
  {
    id: 'ai-design-systems', title: 'AI design systems', category: 'systems', level: 'Intermediate',
    summary: 'Design consistent interfaces for uncertainty, evidence, feedback, and control.',
    explanation: 'An AI design system extends familiar interface patterns to model-driven behavior. It defines how to show sources, communicate uncertainty, collect feedback, expose tool actions, and recover from failure. Interfaces should distinguish drafts from committed actions and support correction when the model is wrong. These patterns need to match the actual capability of the system. A confidence badge or animated status label adds little if users cannot interpret it or act on it.',
    example: 'A writing assistant provides a preview of changes, accessible source links, and an undo path before applying a generated revision.',
    takeaway: 'Make uncertainty and control useful parts of the interaction, not decorative labels.', related: ['agents', 'evaluation', 'rag'], demo: null,
    steps: ['Show the evidence and state that help the user decide.', 'Offer clear controls to inspect, edit, retry, or undo.', 'Collect actionable feedback and test the failure paths.'],
  },
  {
    id: 'mlops', title: 'MLOps & data drift', category: 'systems', level: 'Advanced',
    summary: 'Keep a learning system observable and maintainable after its first release.',
    explanation: 'MLOps connects data, training, evaluation, deployment, and monitoring into a repeatable process. Versioned datasets and artifacts help reproduce results. Production monitoring checks input changes, performance where labels become available, latency, cost, and operational failures. Data drift means the input distribution changed; concept drift means the relationship between inputs and targets changed. Neither should trigger blind retraining without investigation and a validation plan.',
    example: 'A demand model trained in one season is monitored for changing usage patterns and evaluated again when reliable new labels arrive.',
    takeaway: 'Deployment starts an observation loop. It does not finish the learning work.', related: ['data-splits', 'evaluation', 'fine-tuning'], demo: null,
    steps: ['Version the data, code, model, and evaluation results.', 'Deploy with observability and a rollback path.', 'Investigate changes before retraining and promoting a replacement.'],
  },
].map((concept) => ({
  ...concept,
  reading: topicReadings[concept.id] || readings[concept.category === 'machine-learning' ? 'ml' : concept.category === 'deep-learning' ? 'dl' : concept.category === 'llms' ? 'llm' : concept.category],
}));
