// Curated from the original providers. Research and access notes: RESOURCE_SOURCES.md.
export const resources = [
  {
    id: 'linear-algebra',
    title: 'Essence of Linear Algebra',
    provider: '3Blue1Brown',
    type: 'Guide',
    category: 'foundations',
    level: 'Beginner',
    description: 'See vectors, matrices, transformations, and eigenvectors as geometry. Build the visual intuition that makes embeddings, optimization, and neural networks easier to understand.',
    url: 'https://www.3blue1brown.com/?topic=linear-algebra',
    topics: ['Vectors', 'Matrices', 'Eigenvectors'],
    access: 'Free guide',
    format: 'Visual lessons + video',
  },
  {
    id: 'seeing-theory',
    title: 'Seeing Theory',
    provider: 'Brown University',
    type: 'Interactive',
    category: 'foundations',
    level: 'Beginner',
    description: 'Play with probability, distributions, Bayesian inference, and regression through an archived collection of interactive visualizations. Turn abstract statistical ideas into experiments you can see.',
    url: 'https://seeing-theory.brown.edu/',
    topics: ['Probability', 'Statistics', 'Bayes'],
    access: 'Free interactive',
    format: 'Browser experiments',
  },
  {
    id: 'neural-networks',
    title: 'Neural Networks, Visually',
    provider: '3Blue1Brown',
    type: 'Guide',
    category: 'deep-learning',
    level: 'Beginner',
    description: 'Follow the geometry of neurons, gradient descent, and backpropagation before exploring transformers and attention. Animated explanations make the mathematics feel connected and approachable.',
    url: 'https://www.3blue1brown.com/?topic=neural-networks',
    topics: ['Neural networks', 'Backpropagation', 'Attention'],
    access: 'Free guide',
    format: 'Animated video + reading',
  },
  {
    id: 'ml-crash-course',
    title: 'Machine Learning Crash Course',
    provider: 'Google',
    type: 'Course',
    category: 'machine-learning',
    level: 'Beginner',
    description: 'Build a practical foundation in regression, classification, data preparation, embeddings, and model evaluation through short lessons, interactive diagrams, and hands-on programming exercises.',
    url: 'https://developers.google.com/machine-learning/crash-course?hl=en',
    topics: ['Regression', 'Classification', 'Evaluation'],
    access: 'Free course',
    format: 'Video + exercises',
  },
  {
    id: 'cs229',
    title: 'CS229: Machine Learning',
    provider: 'Stanford Engineering Everywhere',
    type: 'Course',
    category: 'machine-learning',
    level: 'Advanced',
    description: 'Study the mathematical foundations of supervised learning, clustering, and reinforcement learning with archived lectures and assignments. A rigorous companion to practical model building.',
    url: 'https://see.stanford.edu/Course/CS229',
    topics: ['Learning theory', 'Clustering', 'Optimization'],
    access: 'Free materials',
    format: 'Archived lectures + assignments',
  },
  {
    id: 'cs50-ai',
    title: 'CS50: AI with Python',
    provider: 'Harvard University',
    type: 'Course',
    category: 'machine-learning',
    level: 'Intermediate',
    description: 'Build Python projects around search, uncertainty, optimization, learning, and language. The OpenCourseWare lessons are free; optional verified certificates and academic credit are separate.',
    url: 'https://cs50.harvard.edu/ai/',
    topics: ['Search', 'Probabilistic reasoning', 'Python'],
    access: 'Free course',
    format: 'Lectures + Python projects',
  },
  {
    id: 'fastai',
    title: 'Practical Deep Learning for Coders',
    provider: 'fast.ai',
    type: 'Course',
    category: 'deep-learning',
    level: 'Beginner',
    description: 'Start by building useful models, then unpack how they work. Explore vision, language, tabular data, and deployment with practical notebooks and a freely readable companion book.',
    url: 'https://course.fast.ai/',
    topics: ['Computer vision', 'Transfer learning', 'PyTorch'],
    access: 'Free course',
    format: 'Video + notebooks',
  },
  {
    id: 'mit-deep-learning',
    title: '6.S191: Introduction to Deep Learning',
    provider: 'MIT',
    type: 'Course',
    category: 'deep-learning',
    level: 'Intermediate',
    description: 'Explore neural network foundations and modern applications with MIT lecture recordings, slides, and programming labs. Practice the ideas through the openly published course materials.',
    url: 'https://introtodeeplearning.com/',
    topics: ['Neural networks', 'Generative models', 'Vision'],
    access: 'Free materials',
    format: 'Lectures + labs',
  },
  {
    id: 'cs231n',
    title: 'CS231n: Deep Learning for Computer Vision',
    provider: 'Stanford University',
    type: 'Course',
    category: 'deep-learning',
    level: 'Advanced',
    description: 'Go deeper into visual recognition, convolutional networks, training, and modern vision architectures. Use public course notes, slides, assignments, and linked lecture recordings for independent study.',
    url: 'https://cs231n.stanford.edu/',
    topics: ['CNNs', 'Computer vision', 'Training'],
    access: 'Free materials',
    format: 'Notes + lectures + assignments',
  },
  {
    id: 'pytorch-basics',
    title: 'PyTorch: Learn the Basics',
    provider: 'PyTorch',
    type: 'Documentation',
    category: 'deep-learning',
    level: 'Beginner',
    description: 'Build a complete image classification workflow while learning tensors, datasets, automatic differentiation, optimization, and model saving. Run the examples locally or in linked notebooks.',
    url: 'https://docs.pytorch.org/tutorials/beginner/basics/intro.html',
    topics: ['Tensors', 'Autograd', 'Training loops'],
    access: 'Free guide',
    format: 'Tutorials + runnable notebooks',
  },
  {
    id: 'hf-llm',
    title: 'The LLM Course',
    provider: 'Hugging Face',
    type: 'Course',
    category: 'llms',
    level: 'Intermediate',
    description: 'Move from tokenizers and transformers to datasets, fine-tuning, and reasoning models. Learn through open lessons and notebooks using the Hugging Face ecosystem.',
    url: 'https://huggingface.co/learn/llm-course/chapter1/1',
    topics: ['Transformers', 'Tokenization', 'Fine-tuning'],
    access: 'Free course',
    format: 'Lessons + notebooks',
  },
  {
    id: 'hf-agents',
    title: 'AI Agents Course',
    provider: 'Hugging Face',
    type: 'Course',
    category: 'llms',
    level: 'Intermediate',
    description: 'Understand tools, actions, observations, and agent workflows. Build with agent libraries, work through practical use cases, and explore evaluation with openly available course lessons.',
    url: 'https://huggingface.co/learn/agents-course/unit0/introduction',
    topics: ['Agents', 'Tool use', 'Evaluation'],
    access: 'Free course',
    format: 'Lessons + agent projects',
  },
  {
    id: 'hf-deep-rl',
    title: 'Deep Reinforcement Learning Course',
    provider: 'Hugging Face',
    type: 'Course',
    category: 'machine-learning',
    level: 'Intermediate',
    description: 'Train agents that learn from rewards and interaction. Connect reinforcement learning theory to hands-on environments, practical notebooks, and community challenges in an open course.',
    url: 'https://huggingface.co/learn/deep-rl-course/unit0/introduction',
    topics: ['Rewards', 'Policies', 'Reinforcement learning'],
    access: 'Free course',
    format: 'Lessons + notebooks + environments',
  },
  {
    id: 'cs224n',
    title: 'CS224N: NLP with Deep Learning',
    provider: 'Stanford University',
    type: 'Course',
    category: 'llms',
    level: 'Advanced',
    description: 'Study word vectors, language models, and neural approaches to language. Follow public notes, assignments, and free lecture archives; enrolled classroom services are separate.',
    url: 'https://web.stanford.edu/class/cs224n/',
    topics: ['NLP', 'Embeddings', 'Language models'],
    access: 'Free materials',
    format: 'Notes + archived lectures',
  },
  {
    id: 'neural-playground',
    title: 'Neural Network Playground',
    provider: 'TensorFlow',
    type: 'Interactive',
    category: 'machine-learning',
    level: 'Beginner',
    description: 'Change layers, features, learning rate, and regularization while a small network trains in your browser. Watch decision boundaries and loss respond to each experiment.',
    url: 'https://playground.tensorflow.org/',
    topics: ['Decision boundaries', 'Overfitting', 'Hyperparameters'],
    access: 'Free interactive',
    format: 'Live browser sandbox',
  },
  {
    id: 'cnn-explainer',
    title: 'CNN Explainer',
    provider: 'Polo Club of Data Science',
    type: 'Interactive',
    category: 'deep-learning',
    level: 'Beginner',
    description: 'Follow an image through a convolutional network and inspect its intermediate operations. Connect filters, activations, and pooling to the predictions a network eventually makes.',
    url: 'https://poloclub.github.io/cnn-explainer/',
    topics: ['Convolution', 'Pooling', 'Feature maps'],
    access: 'Free interactive',
    format: 'Interactive model visualization',
  },
  {
    id: 'transformer-explainer',
    title: 'Transformer Explainer',
    provider: 'Polo Club of Data Science',
    type: 'Interactive',
    category: 'llms',
    level: 'Intermediate',
    description: 'Trace GPT-2 text generation through token embeddings, attention, and output probabilities. Adjust sampling controls and inspect how a transformer chooses its next token.',
    url: 'https://poloclub.github.io/transformer-explainer/',
    topics: ['Attention', 'Sampling', 'Next-token prediction'],
    access: 'Free interactive',
    format: 'Live transformer visualization',
  },
  {
    id: 'feature-visualization',
    title: 'Feature Visualization',
    provider: 'Distill',
    type: 'Guide',
    category: 'deep-learning',
    level: 'Advanced',
    description: 'Explore how optimization can reveal patterns that activate a network. Rich visual examples connect neurons, features, and interpretability while explaining the method\'s limitations.',
    url: 'https://distill.pub/2017/feature-visualization/',
    topics: ['Interpretability', 'Features', 'Optimization'],
    access: 'Free guide',
    format: 'Visual research article',
  },
  {
    id: 'illustrated-transformer',
    title: 'The Illustrated Transformer',
    provider: 'Jay Alammar',
    type: 'Guide',
    category: 'llms',
    level: 'Intermediate',
    description: 'Build an intuitive picture of the original transformer architecture through diagrams of encoders, decoders, queries, keys, values, and multi-head attention, one step at a time.',
    url: 'https://jalammar.github.io/illustrated-transformer/',
    topics: ['Queries and keys', 'Self-attention', 'Transformers'],
    access: 'Free guide',
    format: 'Illustrated walkthrough',
  },
  {
    id: 'fsdl',
    title: 'Full Stack Deep Learning',
    provider: 'The Full Stack',
    type: 'Course',
    category: 'systems',
    level: 'Intermediate',
    description: 'Take a model beyond a notebook. The free 2022 course covers data, experiments, testing, deployment, monitoring, and the engineering decisions behind practical ML products.',
    url: 'https://fullstackdeeplearning.com/course/2022/',
    topics: ['MLOps', 'Deployment', 'Monitoring'],
    access: 'Free course',
    format: 'Lectures + engineering labs',
  },
  {
    id: 'made-with-ml',
    title: 'Made With ML',
    provider: 'Goku Mohandas / Anyscale',
    type: 'Course',
    category: 'systems',
    level: 'Intermediate',
    description: 'Connect ML development with software engineering through open lessons and code covering data, training, evaluation, serving, testing, and CI/CD. Compute and hosted services are separate.',
    url: 'https://madewithml.com/',
    topics: ['MLOps', 'Testing', 'CI/CD'],
    access: 'Free materials',
    format: 'Lessons + GitHub code',
  },
  {
    id: 'people-ai-guidebook',
    title: 'People + AI Guidebook',
    provider: 'Google PAIR',
    type: 'Guide',
    category: 'systems',
    level: 'Beginner',
    description: 'Design AI products around people with patterns, case studies, and worksheets. Explore user needs, calibrated trust, meaningful explanations, feedback, control, and graceful recovery from errors.',
    url: 'https://pair.withgoogle.com/guidebook-v2/',
    topics: ['AI design', 'Trust', 'Human feedback'],
    access: 'Free guide',
    format: 'Design patterns + worksheets',
  },
  {
    id: 'recommendation-systems',
    title: 'Recommendation Systems',
    provider: 'Google',
    type: 'Course',
    category: 'machine-learning',
    level: 'Intermediate',
    description: 'Learn how recommenders retrieve and rank useful items. Connect collaborative filtering, matrix factorization, and deep models to the choices behind personalized recommendations.',
    url: 'https://developers.google.com/machine-learning/recommendation',
    topics: ['Recommenders', 'Matrix factorization', 'Ranking'],
    access: 'Free course',
    format: 'Lessons + exercises',
  },
  {
    id: 'palantir-aip',
    title: 'Palantir AIP: From Data to Actions',
    provider: 'Palantir',
    type: 'Documentation',
    category: 'systems',
    level: 'Intermediate',
    description: 'Explore public documentation for ontology-connected AI workflows, Logic, evaluation, and assistants. Reading is free; using the platform requires a suitable Palantir enrollment.',
    url: 'https://www.palantir.com/docs/foundry/aip/overview',
    topics: ['AIP', 'Ontology', 'Operational AI'],
    access: 'Free guide',
    format: 'Official documentation',
  },
];

export const resourceReviewedAt = '2026-10-09';
